#include <stdio.h> // include stdio.h library
#include <stdlib.h>
#include <time.h>
int whatIsYourChoice(void);
void Delay(int);
int main()
{
    int userguess;
    int i ;
    srand((int)time(0)); // Unique Seed
    int randomNumber = (rand() % 30) + 1;   //generates a number between 1 to 30 
    //printf("%d\n", randomNumber);
    

    printf("Let’s play a guessing game now.\n\n");
    printf("You will get 5 chances to guess the number generated by your computer.\n");
    printf("The number is between 1 and 30 (both inclusive).\n\n");
    printf("After every incorrect guess, you will get a clue.\n\n");
    printf("After 3 chances, you could use an additional clue.\n");
    printf("Best of luck. Let us play.\n\n");

    
     
     for(i = 1; i < 4; ++i)
    {
        userguess = whatIsYourChoice();
        if (i < 3)
        {
        
            if (userguess > randomNumber)
            {
                printf("Go lower\n");

            }
            else if (userguess < randomNumber)
            {
                printf("Go higher\n");
            }
            else
            {
                printf("You got it in %d times – that is impressive\n\n", i);
                Delay(100);
                break;
            }

        } // end of the if statement 
        else
        {
            if (userguess == randomNumber)
            {
                printf("You got it in %d times – that is impressive.\n\n", i );
                Delay(100);
                break;
            }
        }
    }   // end of 1st for loop
    
    if (i > 3) // if the guess are more than 3 then function this wil execute 
    {
        printf("\nLet me give you another clue\n\n");
        if ((randomNumber % 2) == 0) //To know if the random number is even
        {
            printf("----- Think of an even number and----- ");
            if (userguess > randomNumber)
            {
                printf("Go lower\n");
            }
            else {printf("Go higher\n");}
        }
        else  // to know if the random number is odd 
        {
            printf("----- Think of an odd number and----- ");
            if (userguess > randomNumber) 
            {
                printf("Go lower\n");
            }
            else {printf("Go higher\n");}
        }
        printf("\n");

        for(i; i < 6; ++i) // start of a different loop 
        {
            
            userguess = whatIsYourChoice(); // calling the function so that the user can enter their guess
            if (i < 5) // to avoid getting a comment after 5th guess
            {
            
                if (userguess > randomNumber)
                {
                    printf("Go lower\n");
                }
                else if (userguess < randomNumber)
                {
                    printf("Go higher\n");
                }
                else if (userguess == randomNumber)
                {
                    printf("\n");
                    printf("You got it in %d times - good job, you can do better.\n", i);
                    Delay(100);
                    break;
                }
            }
            else if (userguess == randomNumber)
            {
                printf("\n");
                printf("You got it in %d times - good job, you can do better.\n", i);
                Delay(100);
                break;
            }
        
        } // end of the second loop
        printf("\n"); // for white space
        
        if (i > 5) // if all the guesses are wrong then will funciton will execute
        {
            printf("You should have gone ");
            if (userguess > randomNumber)
            {
                printf("lower - the actual number is %d\nSorry - better luck next time\n", randomNumber);
                Delay(100);
            }
            else
            {
                printf("higher - the actual number is %d\nSorry - better luck next time\n", randomNumber);
                Delay(100);
                
            }
            
            
        }

    }
    clock();
    return 0;

}

int whatIsYourChoice(void)
{
    int userguess;
    printf("Pick a number between 1 and 30: ");
    scanf("%d", &userguess);
    return userguess;
}
void Delay(int number_of_seconds)
{
    // Converting time into milli_seconds
    int milli_seconds = 1000 * number_of_seconds;
  
    // Storing start time
    clock_t start_time = clock();
  
    // looping till required time is not achieved
    while (clock() < start_time + milli_seconds);
}